name: Update Cleaned Data

on:
  push:
    paths:
      - '*.xlsx'                 #activates when new .xlsx file appears
      - 'scripts/clean_data.py'  #or if the script itself changes
  workflow_dispatch:             

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: check repository
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: pip install pandas openpyxl

      - name: run data cleaning script
        run: python scripts/clean_data.py

      - name: commit & push the updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cleaned_data.csv
          git commit -m "Automated update: cleaned_data.csv"
          git push
